# Generated by Django 4.2.5 on 2023-11-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uplaoder',
            new_name='uploader',
        ),
    ]
