# Generated by Django 4.2.5 on 2023-11-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_uplaoder_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='job_city',
            field=models.CharField(choices=[('delhi', 'DELHI'), ('mumbai', 'MUMBAI'), ('Banglore', 'BANGLORE')], max_length=50),
        ),
    ]
